### ISSUE TITLE
Some error when training model

### ISSUE THREAD

**Issue by wlhgtc** [andy840314/QANet-pytorch-#2]
Traceback (most recent call last):
  File "main.py", line 335, in <module>
    app.run(main)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 274, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\absl\app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "main.py", line 317, in main
    train_entry(config)
  File "main.py", line 289, in train_entry
    train(model, optimizer, scheduler, train_dataset, dev_dataset, dev_eval_file, iter)
  File "main.py", line 147, in train
    for i, (Cwid, Ccid, Qwid, Qcid, y1, y2, ids) in tqdm(enumerate(dataset),ncols=50):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

This seems occur when train epoch 1.
I could not find the reason，hope could help！

**Comment by wlhgtc** [comment]
By the way， I denote some part about tensorboard(writer)

**Comment by andy840314** [comment]
https://github.com/pytorch/pytorch/issues/2341
You could take a look at this thread. Set dataloader number of workers to 0 to see the actual bug.

**Comment by BITLsy** [comment]
@wlhgtc I face the same problem with Ubuntu but no Windows system.  I fix it by add up the Swap from 1G to 10G
